version: "3.9"
services:
  devenv:
    build:
      context: .
    user: vscode
    working_dir: /workspace
    # stdin_open: true
    # tty: true
    volumes:
      - type: volume
        source: env-data
        target: /workspace
      - type: volume
        source: env-home
        target: /home/vscode
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
volumes:
  env-data:
  env-home:
